apiVersion: v1
kind: Service
metadata:
  name: ingress-controller-nginx
  labels:
    app: ingress-controller-nginx
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.168.2.50
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  selector:
    app: ingress-controller-nginx

    