apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data: 
  HAPROXY_HTTP_PORT: 80
  HAPROXY_HTTPS_PORT: 443
  HAPROXY_STATS_PORT: 10080
  HAPROXY_MAXCONN: 100
  HAPROXY_SERVER_MAXCONN: 100
  HAPROXY_SERVER_HTTPHOSTNAMES: "AuctionWeb1:9080"
  HAPROXY_SERVER_HTTPSHOSTNAMES: "AuctionWeb1:9443"
  HAPROXY_TERMINATETLS: false
  HAPROXY_NBPROC: 1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  template:
    metadata:
      name: haproxy
      labels:
        app: auction
        tier: lb
        impl: haproxy
    spec:
      containers:
      - image: hrosenbe/weathervane-haproxy:1.1.0
        name: tomcat
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: haproxy-config
        ports: 
        - containerPort: 80
          name: httpport
          protocol: TCP
        - containerPort: 443
          name: httpsport
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  type: NodePort
  ports:
  - port: 80
    name: httpport
  - port: 443
    name: httpsport
  selector:
    app: auction
    tier: lb
    impl: haproxy
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: haproxy
spec:
  rules:
  - host: www.weathervane
    http:
      paths:
      - path: /
        backend:
          serviceName: haproxy
          servicePort: 80